[build]
    # we put server/functions inside react so we can do a deploy button for both 
    # netlify only allows a single deploy button (and related toml)
    functions = "server/functions"

    # react and subfolders are the only parts that can be netlify deployed it is our base
    base = "./react/"

    command = "npm run build"

    publish = "build/"

[build.environment]
    # suppress failures for for build warnings
    CI = "false"
    NODE_VERSION = "16"

[template.environment]
    DAILY_API_KEY = "6b89611a89b61bdcdc1d0ff08f055bd6d576c24af8eee80895c0f7105f91c7d6"
